version: 2.1
workflows:
  build:
    name: Build and Test
    environment:
      node: 14 
    scripts:
      - name: Asenna riippuvuudet
        script: |
          cd react_native # Siirry oikeaan hakemistoon
          npm install # Asentaa projektin riippuvuudet NPM:llä
      - name: Suorita testit
        script: |
          npm test # Suorita testit NPM:llä
      - name: Rakenna Android
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
    enable_ssh: true # Ota käyttöön SSH-pääsy

