version: 2.1

# Määritä työprosessit
workflows:
  build:
    name: Build and Test
    environment:
      node: 14 # Node.js:n versio
    scripts:
      - name: Asenna riippuvuudet
        script: |
          cd android
          ./gradlew dependencies
          cd ..
          npm install # Asentaa projektin riippuvuudet NPM:llä
      - name: Suorita testit
        script: |
          npm test # Suorita testit NPM:llä
      - name: Rakenna Android
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk # Polku rakennettuun APK-tiedostoon
